services:
  tigrcorn-com:
    build: .
    container_name: tigrcorn-com
    restart: unless-stopped
    labels:
      site.host: tigrcorn.com
      site.kind: mdwrk-lander
    expose:
      - "80"
    networks:
      dockerwp:
        aliases:
          - tigrcorn-com

networks:
  dockerwp:
    name: dockerwp
    external: true
